language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
cache: pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - python compile_definitions.py
 - python setup.py nosetests --with-coverage
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --coverage-input-type coverage.py
install:
 - pip install -r requirements.txt
after_success:
 - bash build.sh
services:
 - rabbitmq
