language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
script:
 - python compile_definitions.py
 - python setup.py nosetests
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter
after_success:
 - codeclimate-test-reporter
 - bash build.sh
services: rabbitmq
notifications:
   slack: digicort:lbgdFcFmWmHtHKDEMI3FwQK5
