language: python
python:
 - "2.7"
 - "3.5"
 - "pypy"
script:
 - python compile_definitions.py
 - python setup.py nosetests
 - ENABLE_GEVENT=true python setup.py nosetests
install:
 - pip install -r requirements.txt
 - pip install --force-reinstall "coverage>=4.0,<4.4" codeclimate-test-reporter
 - pip install gevent
after_success:
 - codeclimate-test-reporter
 - bash build.sh
services: rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
