language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "nightly"
 - "pypy"
 - "pypy3.5"
cache: pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - python -m compile_definitions
 - python setup.py test
 - python -m stress_tests
install:
 - pip install -r requirements.txt
 - pip install -r stress_tests/requirements.txt
 - pip install yapf
after_success:
 - coverage xml
 - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
 - bash build.sh
services: rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
