version: '3.2'
services:
  amqp:
    image: rabbitmq
  unittest:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - amqp
  stress_tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: python -m stress_tests
    depends_on:
      - amqp
